id: P009652
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-19 20:42:55.727677
source_metadata:
  id: bdr:W22161
  title: ཤན་འདན་སྟག་སེང་ཁ་སྤྲོད
  author: ''
  volumes:
    334c93f13ae8412e9628abc5f760e322:
      image_group_id: I1PD27525
      title: ''
      volume_number: 1
      total_pages: 135
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
